//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public Announcement()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Entrepeneur { get; set; }
        public string Description { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> DateAnnouncement { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Currency { get; set; }
        public Nullable<int> Vizualization { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Image> Images { get; set; }
    }
}
