//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public string FromUserName { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public string ToUserName { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<int> AnnouncementId { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    }
}
